### ISSUE TITLE
Feedback wanted

### ISSUE THREAD

**Issue by casz** [casz/accurev-client-plugin#1]
@itavero mind taking a look?
My goal is to have a lot of tests to avoid breaking things and hopefully write a lot more concise.
The difference between this simple test is insane: 
https://github.com/casz/accurev-client-plugin/blob/fed8a3cae43b9a96e129f0948c6c8a611dab9114/src/test/java/org/jenkinsci/plugins/accurevclient/AccurevClientJavaTest.java 
and
https://github.com/casz/accurev-client-plugin/blob/master/src/test/kotlin/org/jenkinsci/plugins/accurevclient/AccurevClientTest.kt

**Comment by itavero** [comment]
Unfortunately, I'm no longer working for a company that uses AccuRev, so I have no test environment that verify the new plugin.
